<?php

  function get_slogan() {       
    $num = rand() % (77 - 1 + 1) + 1;    
    switch($num) {

      case 1: echo "Asps... very dangerous. You go first.";break;
      case 2: echo "Oh, my friends! I'm so pleased you're not dead!";break;
      case 3: echo "We have top men working on it right now.";break;
      case 4: echo "They're digging in the wrong place!";break;
      case 5: echo "I don't know, I'm makin' this up as I go.";break;
      case 6: echo "Ah, dessert! Chilled monkey brains.";break;
      case 7: echo "I'm very little! You cheat very big!";break;
      case 8: echo "Fortune and glory, kid. Fortune and glory.";break;
      case 9: echo "That's FIVE camels; can't you count?";break;
      case 10: echo "Fly, yes. Land, no.";break;
      case 11: echo "This is intolerable!";break;
      case 12: echo "Whoa, Doc. This is heavy.";break;
      case 13: echo "Roads? Where we're going, we don't need roads.";break;
      case 14: echo "Great Scott!";break;
      case 15: echo "What's a rerun?";break;
      case 16: echo "Hey, you! Get your damn hands off her!";break;
      case 17: echo "What the hell is a gigawatt?";break;
      case 18: echo "Okay. Time circuit's on. Flux capacitor, fluxing.";break;
      case 19: echo "Crazy drunk pedestrians!";break;
      case 20: echo "Never tell me the odds.";break;
      case 21: echo "Who's scruffy-looking?";break;
      case 22: echo "Laugh it up, fuzzball.";break;
      case 23: echo "That's two you owe me junior.";break;
      case 24: echo "Kirk? You're still alive, my old friend?";break;
      case 25: echo "I don't believe in the no-win scenario.";break;
      case 26: echo "Come with me if you want to live.";break;
      case 27: echo "Want a Twinkie, Genghis Khan?";break;
      case 28: echo "Negative, Ghost Rider, the pattern is full.";break;
      case 29: echo "Talk to me, Goose.";break;
      case 30: echo "Sorry, Goose, but it's time to buzz a tower.";break;
      case 31: echo "Too close for missles, I'm switching to guns.";break;
      case 32: echo "Don't cross the streams.";break;
      case 33: echo "Back off, man. I'm a scientist.";break;
      case 34: echo "That's a big Twinkie.";break;
      case 35: echo "We came, we saw, we kicked its ass!";break;
      case 36: echo "Listen... do you smell something?";break;
      case 37: echo "Go get her, Ray!";break;
      case 38: echo "Welcome to the party, pal.";break;
      case 39: echo "Let's see you take *this* under advisement, jerkweed!";break;
      case 40: echo "Happy trails, Hans.";break;
      case 41: echo "Hey, sprechen ze talk?";break;
      case 42: echo "*Shoot* the glass!";break;
      case 43: echo "Get to the Chopper!";break;
      case 44: echo "If it bleeds, we can kill it.";break;
      case 45: echo "I ain't got time to bleed.";break;
      case 46: echo "Killian, here's your Subzero, now plain zero.";break;
      case 47: echo "We're on a mission from God.";break;
      case 48: echo "No, ma'am. We're musicians.";break;
      case 49: echo "The light was yellow, sir.";break;
      case 50: echo "They broke my watch!";break;
      case 51: echo "I bet these cops got SCMODS.";break;
      case 52: echo "Did you get me my Cheez Wiz, boy?";break;
      case 53: echo "Hannibal's on the jazz.";break;
      case 54: echo "I ain't gettin' on no plane!";break;
      case 55: echo "I pity the fool.";break;
      case 56: echo "I got no time for the jibba-jabba.";break;
      case 57: echo "K.I.T.T., I need ya buddy!";break;
      case 58: echo "Keep your scanners peeled.";break;
      case 59: echo "We're in the pipe, five by five.";break;
      case 60: echo "That's it, man. Game over, man! Game over!";break;
      case 61: echo "I'd buy that for a dollar!";break;
      case 62: echo "Dead or alive, you're coming with me!";break;
      case 63: echo "Your move, creep.";break;
      case 64: echo "Call me 'Snake'";break;
      case 65: echo "The name's Plissken!";break;
      case 66: echo "I have come here to chew bubblegum and kick ass.";break;
      case 67: echo "Mama don't like tattletales.";break;
      case 68: echo "Put the glasses on! Put 'em on!";break;
      case 69: echo "Wouldn't you prefer a nice game of chess?";break;
      case 70: echo "Wolverines!";break;
      case 71: echo "There can be only one!";break;
      case 72: echo "Say hello to my little friend!";break;
      case 73: echo "Goonies never say die!";break;
      case 74: echo "That's right, I'm Abe Froman.";break;
      case 75: echo "They've gone to plaid!";break;
      case 76: echo "LUDICROUS SPEED! *GO!*";break;
      case 77: echo "Yippie ki-yay.";break;
      default: echo "Yippie ki-yay.";break;
      /*case 1: echo "I said NO camels! That's FIVE camels; can't you count?";break;
      case 2: echo "I aim to misbehave.";break;
      case 3: echo "Do I feel lucky?&nbsp;&nbsp;Well, do ya, punk?";break;
      case 4: echo "Say 'what' again, I dare you.";break;
      case 5: echo "Who am I? Sho'nuff!";break;
      case 6: echo "Knowledge is power. For real.";break;
      case 7: echo "Go ahead, make my day.";break;
      case 8: echo "Get to the chopper!";break;
      case 9: echo "I ain't got time to bleed.";break;
      case 10: echo "Whoa Doc, this is heavy.";break;
      case 11: echo "What the hell is a Gigawatt?";break;
      case 12: echo "Fortune and glory, kid. Fortune and glory.";break;
      case 13: echo "Fly, yes. Land, no";break;
      case 14: echo "You have chosen... wisely.";break;
      case 15: echo "Welcome to the party, pal.";break;
      case 16: echo "Who's scruffy-looking?";break;
      case 17: echo "Laugh it up, fuzzball.";break;
      case 18: echo "That's just crazy enough to work.";break;
      case 19: echo "They broke my watch! ";break;
      case 20: echo "I hate Illinois Nazis.";break;
      case 21: echo "We're on a mission from God.";break;
      case 22: echo "The light was yellow, sir.";break;
      case 23: echo "No, ma'am. We're musicians.";break;
      case 24: echo "Asps... very dangerous. You go first.";break;
      case 25: echo "Great Scott!";break;
      case 26: echo "Otis! My man!";break;
      case 27: echo "That'll do pig. That'll do.";break;
      case 28: echo "Don't be so gullible, McFly.";break;
      case 29: echo "Time circuit's on. Flux Capacitor... fluxing.";break;
      case 30: echo "Welcome to Earth!";break;
      case 31: echo "T.C.B., baby.";break;
      case 32: echo "Thank you, thank you very much.";break;
      case 33: echo "I smell T-r-o-u-b-l-e.";break;
      case 34: echo "Gimme some sugar, baby.";break;
      case 35: echo "Alright. Who wants some?";break;
      case 36: echo "This... is my boomstick!";break;
      case 37: echo "*Shoot* the glass!";break;
      case 38: echo "Hannibal's on the jazz.";break;
      case 39: echo "I ain't gettin' on no plane!";break;
      case 40: echo "I pity the fool.";break;
      case 41: echo "I got no time for the jibba-jabba.";break;
      case 42: echo "You can't stop the signal.";break;
      case 43: echo "I bet these cops got SCMODS.";break;
      case 44: echo "You get me my Cheez Wiz, boy?";break;
      case 45: echo "I found it in Tobin's Spirit Guide.";break;
      case 46: echo "Don't cross the streams.";break;
      case 47: echo "Back off, man. I'm a scientist.";break;
      case 48: echo "That's a big Twinkie.";break;
      case 49: echo "Ain't gonna be no rematch.";break;
      case 50: echo "I ain't no bum, Mick.";break;
      case 51: echo "You've just been erased.";break;
      case 52: echo "Come with me if you want to live.";break;
      case 53: echo "Over my dead body!";break;
      case 54: echo "Never tell me the odds.";break;
      case 55: echo "That's two you owe me junior.";break;
      case 56: echo "Do a barrel roll!";break;
      case 57: echo "Say your prayers, Andross.";break;
      case 58: echo "Mama don't like tattletales.";break;
      case 59: echo "Great White Buffalo.";break;
      case 60: echo "Too close for missles, I'm switching to guns.";break;
      case 61: echo "That's a negative, Ghost Rider.";break;
      case 62: echo "Crazy drunk pedestrians!";break;
      case 63: echo "Manure! I hate manure!";break;
      case 64: echo "You're the doc, Doc.";break;
      case 65: echo "Go get her, Ray!";break;
      case 66: echo "You betrayed Shiva!";break;
      case 67: echo "Kali ma, shakthi deh!";break;
      case 68: echo "Nazis. I hate these guys.";break;
      case 69: echo "This is intolerable!";break;
      case 70: echo "Hold on to your butts.";break;
      case 71: echo "Dino D-N-A.";break;
      case 72: echo "Clever girl.";break;
      case 73: echo "You bred raptors?";break;
      case 74: echo "Welcome to The Rock.";break;
      case 75: echo "Only borrowing your Hum-Vee!";break;
      case 76: echo "Trade secrets, my son.";break;
      case 77: echo "Come on, don't bullshit me.";break;
      case 78: echo "Hack the planet!";break;
      case 79: echo "My name is Inigo Montoya. You killed my father. Prepare to die.";break;
      case 80: echo "You're going to need a bigger boat.";break;
      case 81: echo "Smile, you son of a bitch.";break;
      case 82: echo "That's no moon!";break;
      case 83: echo "We're in the pipe, five by five.";break;   
      case 84: echo "What's a rerun?";break;  
      case 85: echo "Hail to the king, baby.";break;  
      case 86: echo "Call me 'Snake'.";break;
      case 87: echo "You all are Browncoats, eh?";break;
      case 88: echo "Where we're going, we don't need... roads.";break;
      case 89: echo "Hey, sprechen ze talk?";break;
      case 90: echo "I'm a zit, get it?";break;
      case 91: echo "Toga, toga, to-ga!";break;
      case 92: echo "Well, if it isn't Lone Star.";break;
      case 93: echo "They've gone to plaid!";break;
      case 94: echo "Ludicrous speed! *GO!*";break;
      case 95: echo "Comingtoyaaaahaaaa!";break;
      case 96: echo "Die, replacement-friends!";break;
      case 97: echo "Sweet Lincoln's mullet!";break;
      case 98: echo "Great Odin's raven!";break;
      case 99: echo "Como estan, beetches?";break;
      case 100: echo "Eye of the tiger, man.";break;
      case 101: echo "I must break you.";break;
      case 102: echo "I love lamp.";break;
      case 103: echo "By the beard of Zeus!";break;
      case 104: echo "Get off my lawn.";break;
      case 105: echo "When this baby hits 88mph...  you're gonna see some serious shit.";break;
      case 106: echo "I'd buy that for a dollar!";break;
      case 107: echo "Red five, standing by.";break;
      case 108: echo "Yo, she-bitch! Let's go!";break;
      case 109: echo "Come get some."; break;
      case 110: echo "KITT, I need you buddy."; break;
      case 111: echo "Run home and cry to mama!";break;
      case 112: echo "If it bleeds, we can kill it.";break;
      case 113: echo "This is a tasty burger!";break;
      case 114: echo "Great, kid. Don't get cocky.";break;
      case 115: echo "Yippie ki-yay.";break;
      default: echo "I aim to misbehave.";break;*/
    } 

  }

?>